# data loading
training_size: 10000
batch_size: 64
num_workers: 8

# model
meta_hidden_size: 4

# baselearner training
b_epoch: 100
b_lr: 0.01

# metalearner training
m_epoch: 5
m_lr: 0.01
T: 10
p: 10
